/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package basisdata;

import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import java.text.ParseException;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author aril
 */
public class detailPenyewaan extends javax.swing.JFrame {
    PreparedStatement pst = null;
    ResultSet rs;
    Statement st;
    Connection con;
    final DefaultTableModel dtm;
    
    public detailPenyewaan(String noTrans) {
        initComponents();
        lbl_noTrans1.setText(noTrans);
        
        dtm = new DefaultTableModel();
        table_DetailPenyewaan.setModel(dtm);
        dtm.addColumn("Nomor Transaksi");
        dtm.addColumn("Nomor Polisi");
        dtm.addColumn("Tanggal Sewa");
        dtm.addColumn("Tanggal Berakhir");
        dtm.addColumn("Batas Waktu");
        dtm.addColumn("Total Harga");
        dtm.addColumn("Jam Ambil");
        dtm.addColumn("Jam Kembali");
        dtm.addColumn("Tujuan");
        update_table();
//        no_transaksi();
        nopol();
    }
    
//    public void no_transaksi(){
//        try{
//            con = Basisdata.getKoneksi();
//            st = con.createStatement();
//            String sql = "SELECT No_Transaksi FROM Penyewaan";
//            rs = st.executeQuery(sql);
//            
//            while(rs.next()){
//                String noTrans = rs.getString("No_Transaksi");
//                box_noTrans.addItem(noTrans);
//            }
//        }
//        catch(SQLException e){
//            Logger.getLogger(detailPenyewaan.class.getName()).log(Level.SEVERE, null, e);
//        }
//    }
    
    public void nopol(){
        try{
            con = Basisdata.getKoneksi();
            st = con.createStatement();
            String sql = "SELECT No_Polisi FROM Kendaraan";
            rs = st.executeQuery(sql);
            
            while(rs.next()){
                String nopol = rs.getString("No_Polisi");
                box_nopol.addItem(nopol);
            }
        }
        catch(SQLException e){
            Logger.getLogger(detailPenyewaan.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        box_nopol = new javax.swing.JComboBox<>();
        btn_Tambah = new javax.swing.JButton();
        btn_Hapus = new javax.swing.JButton();
        btn_Edit = new javax.swing.JButton();
        btn_Kembali = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_cari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_DetailPenyewaan = new javax.swing.JTable();
        btn_Clear = new javax.swing.JButton();
        lbl_nopol = new javax.swing.JLabel();
        lbl_unit = new javax.swing.JLabel();
        label_harga = new javax.swing.JLabel();
        lbl_tglSewa = new javax.swing.JLabel();
        lbl_tglBerakhir = new javax.swing.JLabel();
        lbl_btsWkt = new javax.swing.JLabel();
        tglBerakhir = new com.toedter.calendar.JDateChooser();
        tglSewa = new com.toedter.calendar.JDateChooser();
        txt_btsWaktu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lbl_jamAmbil = new javax.swing.JLabel();
        lbl_jamKembali = new javax.swing.JLabel();
        lbl_tujuan = new javax.swing.JLabel();
        txt_jamAmbil = new javax.swing.JTextField();
        txt_tujuan = new javax.swing.JTextField();
        txt_jamKembali = new javax.swing.JTextField();
        lbl_noTrans = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_unit1 = new javax.swing.JLabel();
        lbl_harga1 = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        lbl_noTrans1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("1001 Trans Malang");

        jPanel1.setBackground(new java.awt.Color(200, 49, 49));

        judul.setFont(new java.awt.Font("Ubisoft Sans", 1, 36)); // NOI18N
        judul.setText("DETAIL PENYEWAAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(judul)
                .addGap(353, 353, 353))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judul, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(33, 213, 33));

        box_nopol.setFont(new java.awt.Font("Ubisoft Sans", 0, 12)); // NOI18N
        box_nopol.setPreferredSize(new java.awt.Dimension(72, 50));
        box_nopol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_nopolActionPerformed(evt);
            }
        });

        btn_Tambah.setBackground(new java.awt.Color(49, 49, 186));
        btn_Tambah.setFont(new java.awt.Font("Ubisoft Sans", 1, 12)); // NOI18N
        btn_Tambah.setForeground(new java.awt.Color(255, 255, 255));
        btn_Tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plus.png"))); // NOI18N
        btn_Tambah.setText("TAMBAH DATA");
        btn_Tambah.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TambahActionPerformed(evt);
            }
        });

        btn_Hapus.setBackground(new java.awt.Color(49, 49, 186));
        btn_Hapus.setFont(new java.awt.Font("Ubisoft Sans", 1, 12)); // NOI18N
        btn_Hapus.setForeground(new java.awt.Color(255, 255, 255));
        btn_Hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/trash_box.png"))); // NOI18N
        btn_Hapus.setText("HAPUS DATA");
        btn_Hapus.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HapusActionPerformed(evt);
            }
        });

        btn_Edit.setBackground(new java.awt.Color(49, 49, 186));
        btn_Edit.setFont(new java.awt.Font("Ubisoft Sans", 1, 12)); // NOI18N
        btn_Edit.setForeground(new java.awt.Color(255, 255, 255));
        btn_Edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pencil_edit.png"))); // NOI18N
        btn_Edit.setText("EDIT DATA");
        btn_Edit.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditActionPerformed(evt);
            }
        });

        btn_Kembali.setFont(new java.awt.Font("Ubisoft Sans", 1, 12)); // NOI18N
        btn_Kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/arrow_left.png"))); // NOI18N
        btn_Kembali.setText("BACK");
        btn_Kembali.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KembaliActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Ubisoft Sans", 0, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search_lense.png"))); // NOI18N
        jLabel1.setText("CARI");

        txt_cari.setFont(new java.awt.Font("Ubisoft Sans", 0, 12)); // NOI18N
        txt_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txt_cari, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_cari))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        table_DetailPenyewaan.setBackground(new java.awt.Color(200, 49, 49));
        table_DetailPenyewaan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 49, 49), 1, true));
        table_DetailPenyewaan.setFont(new java.awt.Font("Ubisoft Sans", 0, 12)); // NOI18N
        table_DetailPenyewaan.setForeground(new java.awt.Color(255, 255, 255));
        table_DetailPenyewaan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        table_DetailPenyewaan.setGridColor(new java.awt.Color(255, 255, 255));
        table_DetailPenyewaan.setRowHeight(25);
        table_DetailPenyewaan.setSelectionBackground(new java.awt.Color(204, 204, 204));
        table_DetailPenyewaan.setShowGrid(true);
        table_DetailPenyewaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_DetailPenyewaanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_DetailPenyewaan);

        btn_Clear.setBackground(new java.awt.Color(49, 49, 186));
        btn_Clear.setFont(new java.awt.Font("Ubisoft Sans", 1, 12)); // NOI18N
        btn_Clear.setForeground(new java.awt.Color(255, 255, 255));
        btn_Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/refresh.png"))); // NOI18N
        btn_Clear.setText("CLEAR");
        btn_Clear.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClearActionPerformed(evt);
            }
        });

        lbl_nopol.setFont(new java.awt.Font("Ubisoft Sans", 0, 14)); // NOI18N
        lbl_nopol.setText("NO POLISI                        :");

        lbl_unit.setFont(new java.awt.Font("Ubisoft Sans", 0, 14)); // NOI18N
        lbl_unit.setText("UNIT                                   :");

        label_harga.setFont(new java.awt.Font("Ubisoft Sans", 0, 14)); // NOI18N
        label_harga.setText("HARGA SEWA/HARI    :");

        lbl_tglSewa.setFont(new java.awt.Font("Ubisoft Sans", 0, 14)); // NOI18N
        lbl_tglSewa.setText("TANGGAL SEWA              :");

        lbl_tglBerakhir.setFont(new java.awt.Font("Ubisoft Sans", 0, 14)); // NOI18N
        lbl_tglBerakhir.setText("TANGGAL BERAKHIR      :");

        lbl_btsWkt.setFont(new java.awt.Font("Ubisoft Sans", 0, 14)); // NOI18N
        lbl_btsWkt.setText("BATAS WAKTU                  :");

        tglBerakhir.setDateFormatString("yyyy-MM-dd");

        tglSewa.setDateFormatString("yyyy-MM-dd");

        txt_btsWaktu.setFont(new java.awt.Font("Ubisoft Sans", 0, 12)); // NOI18N
        txt_btsWaktu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_btsWaktuActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Ubisoft Sans", 0, 14)); // NOI18N
        jLabel5.setText("HARI");

        lbl_jamAmbil.setFont(new java.awt.Font("Ubisoft Sans", 0, 14)); // NOI18N
        lbl_jamAmbil.setText("JAM AMBIL         :");

        lbl_jamKembali.setFont(new java.awt.Font("Ubisoft Sans", 0, 14)); // NOI18N
        lbl_jamKembali.setText("JAM KEMBALI    :");

        lbl_tujuan.setFont(new java.awt.Font("Ubisoft Sans", 0, 14)); // NOI18N
        lbl_tujuan.setText("  TUJUAN                :");

        txt_jamAmbil.setFont(new java.awt.Font("Ubisoft Sans", 0, 12)); // NOI18N
        txt_jamAmbil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jamAmbilActionPerformed(evt);
            }
        });

        txt_tujuan.setFont(new java.awt.Font("Ubisoft Sans", 0, 12)); // NOI18N

        txt_jamKembali.setFont(new java.awt.Font("Ubisoft Sans", 0, 12)); // NOI18N

        lbl_noTrans.setFont(new java.awt.Font("Ubisoft Sans", 0, 14)); // NOI18N
        lbl_noTrans.setText("NO TRANSAKSI              :");

        jLabel2.setFont(new java.awt.Font("Ubisoft Sans", 0, 14)); // NOI18N
        jLabel2.setText("TOTAL HARGA                  :");

        lbl_unit1.setFont(new java.awt.Font("Ubisoft Sans", 0, 14)); // NOI18N

        lbl_harga1.setFont(new java.awt.Font("Ubisoft Sans", 0, 14)); // NOI18N

        lbl_total.setFont(new java.awt.Font("Ubisoft Sans", 0, 14)); // NOI18N

        lbl_noTrans1.setFont(new java.awt.Font("Ubisoft Sans", 0, 14)); // NOI18N
        lbl_noTrans1.setText("jLabel3");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btn_Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 942, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(label_harga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_unit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lbl_nopol)
                            .addComponent(lbl_noTrans))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(box_nopol, 0, 150, Short.MAX_VALUE)
                            .addComponent(lbl_unit1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_harga1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_noTrans1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_total, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(lbl_btsWkt)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_btsWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_tujuan))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(lbl_tglSewa)
                                        .addGap(18, 18, 18)
                                        .addComponent(tglSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_jamAmbil, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(lbl_tglBerakhir)
                                        .addGap(18, 18, 18)
                                        .addComponent(tglBerakhir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)
                                        .addComponent(lbl_jamKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_jamKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_jamAmbil, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_tujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tglSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_jamAmbil, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_jamAmbil))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_noTrans)
                            .addComponent(lbl_noTrans1)
                            .addComponent(lbl_tglSewa))
                        .addGap(8, 8, 8)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_jamKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_jamKembali)))
                    .addComponent(tglBerakhir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(box_nopol, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_nopol)
                        .addComponent(lbl_tglBerakhir)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_unit1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_btsWkt)
                        .addComponent(txt_btsWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(lbl_tujuan)
                        .addComponent(txt_tujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_unit)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_harga)
                    .addComponent(jLabel2)
                    .addComponent(lbl_harga1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_total))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TambahActionPerformed
        SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
        String nomTrans = lbl_noTrans1.getText();
        String nopol = box_nopol.getSelectedItem().toString();
        String tgl1 = date.format(tglSewa.getDate());
        String tgl2 = date.format(tglBerakhir.getDate());
        String btsWaktu = txt_btsWaktu.getText();
        String total = lbl_total.getText();
        String jamAmbil = txt_jamAmbil.getText();
        String jamKembali = txt_jamKembali.getText();
        String tujuan = txt_tujuan.getText();

        if (tgl1==null || tgl2==null || jamAmbil.isEmpty() || jamKembali.isEmpty() || tujuan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mohon lengkapi semua data", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        con = Basisdata.getKoneksi();
        String sql = "INSERT INTO DetailPenyewaan (No_Transaksi, No_Polisi, Tanggal_Sewa, Tanggal_Berakhir, Batas_Waktu, Total, Jam_Ambil, Jam_Kembali, Tujuan) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
        try{
            pst = con.prepareStatement(sql);
            pst.setString(1, nomTrans);
            pst.setString(2, nopol);
            pst.setString(3, tgl1);
            pst.setString(4, tgl2);
            pst.setString(5, btsWaktu);
            pst.setString(6, total);
            pst.setString(7, jamAmbil);
            pst.setString(8, jamKembali);
            pst.setString(9, tujuan);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil ditambah", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        clear();
        update_table();
    }//GEN-LAST:event_btn_TambahActionPerformed

    private void btn_KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KembaliActionPerformed
        new Penyewaan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_KembaliActionPerformed

    private void txt_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cariActionPerformed
        cari();
    }//GEN-LAST:event_txt_cariActionPerformed

    private void txt_btsWaktuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_btsWaktuActionPerformed
        selisih();
    }//GEN-LAST:event_txt_btsWaktuActionPerformed

    private void txt_jamAmbilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jamAmbilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jamAmbilActionPerformed

    private void btn_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClearActionPerformed
        clear();
    }//GEN-LAST:event_btn_ClearActionPerformed

    private void box_nopolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_nopolActionPerformed
        String nopol = box_nopol.getSelectedItem().toString();
        try{
            con = Basisdata.getKoneksi();
            Statement st = con.createStatement();
            String sql = "SELECT * FROM Kendaraan WHERE No_Polisi ='"+nopol+"'";
            ResultSet rs = st.executeQuery(sql);
            if (rs.next()){
                lbl_unit1.setText(rs.getString("Unit"));
                lbl_harga1.setText(rs.getString("Harga_Sewa_Per_Hari"));
            }
        } 
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_box_nopolActionPerformed

    private void btn_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HapusActionPerformed
        String nomTrans = lbl_noTrans1.getText();

        int selectedOption = JOptionPane.showConfirmDialog(null, "Hapus data dengan nomor Transaksi : "+nomTrans+"?","Konformasi", JOptionPane.INFORMATION_MESSAGE);
        if(selectedOption == JOptionPane.YES_OPTION){
            con = Basisdata.getKoneksi();
            try{
                String sql = "DELETE FROM DetailPenyewaan WHERE No_Transaksi=?";
                pst = con.prepareStatement(sql);
                pst.setString(1, nomTrans);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
            } 
            catch(SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        clear();
        update_table();
    }//GEN-LAST:event_btn_HapusActionPerformed

    private void btn_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditActionPerformed
        SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
        String nomTrans = lbl_noTrans1.getText();
        String nopol = box_nopol.getSelectedItem().toString();
        String tgl1 = date.format(tglSewa.getDate());
        String tgl2 = date.format(tglBerakhir.getDate());
        String btsWaktu = txt_btsWaktu.getText();
        String total = lbl_total.getText();
        String jamAmbil = txt_jamAmbil.getText();
        String jamKembali = txt_jamKembali.getText();
        String tujuan = txt_tujuan.getText();

        if (tgl1.isEmpty() || tgl2.isEmpty() || jamAmbil.isEmpty() || jamKembali.isEmpty() || tujuan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mohon lengkapi semua data", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String sql = "UPDATE DetailPenyewaan SET No_Polisi=?, Tanggal_Sewa=?, Tanggal_Berakhir=?, Batas_Waktu=?, Total=?, Jam_Ambil=?, Jam_Kembali=?, Tujuan=? WHERE No_Transaksi=?";
        try{
            pst = con.prepareStatement(sql);
            pst.setString(1, nopol);
            pst.setString(2, tgl1);
            pst.setString(3, tgl2);
            pst.setString(4, btsWaktu);
            pst.setString(5, total);
            pst.setString(6, jamAmbil);
            pst.setString(7, jamKembali);
            pst.setString(8, tujuan);
            pst.setString(9, nomTrans);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil diedit", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        clear();
        update_table();
    }//GEN-LAST:event_btn_EditActionPerformed

    private void table_DetailPenyewaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_DetailPenyewaanMouseClicked
        DefaultTableModel tabel = (DefaultTableModel) table_DetailPenyewaan.getModel();
        int selectedIndex = table_DetailPenyewaan.getSelectedRow();
        
        SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
        String tanggalSewaStr = tabel.getValueAt(selectedIndex, 2).toString();
        String tanggalBerakhirStr = tabel.getValueAt(selectedIndex, 3).toString();
        try {
            Date tanggalSewa = date.parse(tanggalSewaStr);
            Date tanggalBerakhir = date.parse(tanggalBerakhirStr);
            lbl_noTrans1.setText(tabel.getValueAt(selectedIndex, 0).toString());
            box_nopol.setSelectedItem(tabel.getValueAt(selectedIndex, 1).toString());
            tglSewa.setDate(tanggalSewa);
            tglBerakhir.setDate(tanggalBerakhir);
            txt_btsWaktu.setText(tabel.getValueAt(selectedIndex, 4).toString());
            lbl_total.setText(tabel.getValueAt(selectedIndex, 5).toString());
            txt_jamAmbil.setText(tabel.getValueAt(selectedIndex, 6).toString());
            txt_jamKembali.setText(tabel.getValueAt(selectedIndex, 7).toString());
            txt_tujuan.setText(tabel.getValueAt(selectedIndex, 8).toString());
        } catch (ParseException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_table_DetailPenyewaanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(detailPenyewaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(detailPenyewaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(detailPenyewaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(detailPenyewaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new detailPenyewaan("").setVisible(true);
            }
        });
    }
    
    private void clear() {
        tglSewa.setDate(null);
        tglBerakhir.setDate(null);
        txt_btsWaktu.setText("");
        lbl_total.setText("");
        txt_jamAmbil.setText("");
        txt_jamKembali.setText("");
        txt_tujuan.setText("");
    }
    
    private void cari(){
        try{
            st = Basisdata.getKoneksi().createStatement();
            rs = st.executeQuery("SELECT * FROM DetailPenyewaan WHERE No_Transaksi LIKE '%"+txt_cari.getText()+"%'");
            dtm.getDataVector().removeAllElements();
            while(rs.next()){
                Object[] x = new Object[9];
                    x[0] = rs.getString("No_Transaksi");
                    x[1] = rs.getString("No_Polisi");
                    x[2] = rs.getString("Tanggal_Sewa");
                    x[3] = rs.getString("Tanggal_Berakhir");
                    x[4] = rs.getString("Batas_Waktu");
                    x[5] = rs.getString("Total");
                    x[6] = rs.getString("Jam_Ambil");
                    x[7] = rs.getString("Jam_Kembali");
                    x[8] = rs.getString("Tujuan");
                    dtm.addRow(x);
            }
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi error", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    private void update_table(){
        dtm.getDataVector().removeAllElements();
        dtm.fireTableDataChanged();
        try{
            con = Basisdata.getKoneksi();
            try(Statement s = con.createStatement()){
                String sql = "SELECT * FROM DetailPenyewaan";
                rs = s.executeQuery(sql);
                while(rs.next()){
                    Object[] x = new Object[9];
                    x[0] = rs.getString("No_Transaksi");
                    x[1] = rs.getString("No_Polisi");
                    x[2] = rs.getString("Tanggal_Sewa");
                    x[3] = rs.getString("Tanggal_Berakhir");
                    x[4] = rs.getString("Batas_Waktu");
                    x[5] = rs.getString("Total");
                    x[6] = rs.getString("Jam_Ambil");
                    x[7] = rs.getString("Jam_Kembali");
                    x[8] = rs.getString("Tujuan");
                    dtm.addRow(x);
                }
                rs.close();
            }
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error");
        }
    }
    
    private void selisih(){
        try {
            SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
            String tgl1 = date.format(tglSewa.getDate());
            String tgl2 = date.format(tglBerakhir.getDate());
            Date tglAwal = date.parse(tgl1);
            Date tglBerakhir = date.parse(tgl2);
            long hari1 = tglAwal.getTime();
            long hari2 = tglBerakhir.getTime();
            long bedaHari = hari2 - hari1;
            long btsWaktu = bedaHari / (24 * 60 * 60 * 1000);
            String hasil = (Long.toString(btsWaktu));
            txt_btsWaktu.setText(hasil);

            int harga_sewa = Integer.parseInt(lbl_harga1.getText()); 
            int btsWaktu_sewa = Integer.parseInt(txt_btsWaktu.getText());   
            int Total = harga_sewa * btsWaktu_sewa;                     
            String a = Integer.toString(Total);
            lbl_total.setText(a);
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Masukan Tanggal Sewa dan Tanggal Berakhir");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> box_nopol;
    private javax.swing.JButton btn_Clear;
    private javax.swing.JButton btn_Edit;
    private javax.swing.JButton btn_Hapus;
    private javax.swing.JButton btn_Kembali;
    private javax.swing.JButton btn_Tambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel label_harga;
    private javax.swing.JLabel lbl_btsWkt;
    private javax.swing.JLabel lbl_harga1;
    private javax.swing.JLabel lbl_jamAmbil;
    private javax.swing.JLabel lbl_jamKembali;
    private javax.swing.JLabel lbl_noTrans;
    private javax.swing.JLabel lbl_noTrans1;
    private javax.swing.JLabel lbl_nopol;
    private javax.swing.JLabel lbl_tglBerakhir;
    private javax.swing.JLabel lbl_tglSewa;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JLabel lbl_tujuan;
    private javax.swing.JLabel lbl_unit;
    private javax.swing.JLabel lbl_unit1;
    private javax.swing.JTable table_DetailPenyewaan;
    private com.toedter.calendar.JDateChooser tglBerakhir;
    private com.toedter.calendar.JDateChooser tglSewa;
    private javax.swing.JTextField txt_btsWaktu;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_jamAmbil;
    private javax.swing.JTextField txt_jamKembali;
    private javax.swing.JTextField txt_tujuan;
    // End of variables declaration//GEN-END:variables
}
