/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package basisdata;

import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aril
 */
public class Kendaraan extends javax.swing.JFrame {
    PreparedStatement pst = null;
    ResultSet rs;
    Statement st;
    Connection con;
    final DefaultTableModel dtm;
    
    public Kendaraan() {
        initComponents();
        dtm = new DefaultTableModel();
        table_Kendaraan.setModel(dtm);
        dtm.addColumn("Nomor Polisi");
        dtm.addColumn("Unit");
        dtm.addColumn("Harga Sewa per Hari");
        update_table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txt_nopol = new javax.swing.JTextField();
        txt_unit = new javax.swing.JTextField();
        txt_harga = new javax.swing.JTextField();
        btn_Tambah = new javax.swing.JButton();
        btn_Hapus = new javax.swing.JButton();
        btn_Edit = new javax.swing.JButton();
        btn_Kembali = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_cari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Kendaraan = new javax.swing.JTable();
        btn_Clear = new javax.swing.JButton();
        lbl_nopol = new javax.swing.JLabel();
        lbl_unit = new javax.swing.JLabel();
        lbl_harga = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("1001 Trans Malang");
        setPreferredSize(new java.awt.Dimension(1100, 800));
        setSize(new java.awt.Dimension(1100, 800));

        jPanel1.setBackground(new java.awt.Color(200, 49, 49));

        judul.setFont(new java.awt.Font("Ubisoft Sans", 1, 36)); // NOI18N
        judul.setText("DATA KENDARAAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(375, 375, 375)
                .addComponent(judul)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judul, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(215, 36, 215));

        txt_nopol.setFont(new java.awt.Font("Ubisoft Sans", 0, 14)); // NOI18N
        txt_nopol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nopolActionPerformed(evt);
            }
        });

        txt_unit.setFont(new java.awt.Font("Ubisoft Sans", 0, 14)); // NOI18N
        txt_unit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_unitActionPerformed(evt);
            }
        });

        txt_harga.setFont(new java.awt.Font("Ubisoft Sans", 0, 14)); // NOI18N
        txt_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hargaActionPerformed(evt);
            }
        });

        btn_Tambah.setBackground(new java.awt.Color(49, 49, 186));
        btn_Tambah.setFont(new java.awt.Font("Ubisoft Sans", 1, 12)); // NOI18N
        btn_Tambah.setForeground(new java.awt.Color(255, 255, 255));
        btn_Tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plus.png"))); // NOI18N
        btn_Tambah.setText("TAMBAH DATA");
        btn_Tambah.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TambahActionPerformed(evt);
            }
        });

        btn_Hapus.setBackground(new java.awt.Color(49, 49, 186));
        btn_Hapus.setFont(new java.awt.Font("Ubisoft Sans", 1, 12)); // NOI18N
        btn_Hapus.setForeground(new java.awt.Color(255, 255, 255));
        btn_Hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/trash_box.png"))); // NOI18N
        btn_Hapus.setText("HAPUS DATA");
        btn_Hapus.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HapusActionPerformed(evt);
            }
        });

        btn_Edit.setBackground(new java.awt.Color(49, 49, 186));
        btn_Edit.setFont(new java.awt.Font("Ubisoft Sans", 1, 12)); // NOI18N
        btn_Edit.setForeground(new java.awt.Color(255, 255, 255));
        btn_Edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pencil_edit.png"))); // NOI18N
        btn_Edit.setText("EDIT DATA");
        btn_Edit.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditActionPerformed(evt);
            }
        });

        btn_Kembali.setFont(new java.awt.Font("Ubisoft Sans", 1, 12)); // NOI18N
        btn_Kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/arrow_left.png"))); // NOI18N
        btn_Kembali.setText("BACK");
        btn_Kembali.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KembaliActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Ubisoft Sans", 0, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search_lense.png"))); // NOI18N
        jLabel1.setText("CARI");

        txt_cari.setFont(new java.awt.Font("Ubisoft Sans", 0, 12)); // NOI18N
        txt_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txt_cari, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_cari))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        table_Kendaraan.setBackground(new java.awt.Color(200, 49, 49));
        table_Kendaraan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 49, 49), 1, true));
        table_Kendaraan.setFont(new java.awt.Font("Ubisoft Sans", 0, 14)); // NOI18N
        table_Kendaraan.setForeground(new java.awt.Color(255, 255, 255));
        table_Kendaraan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        table_Kendaraan.setGridColor(new java.awt.Color(255, 255, 255));
        table_Kendaraan.setName(""); // NOI18N
        table_Kendaraan.setRowHeight(25);
        table_Kendaraan.setSelectionBackground(new java.awt.Color(204, 204, 204));
        table_Kendaraan.setShowGrid(true);
        table_Kendaraan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_KendaraanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_Kendaraan);

        btn_Clear.setBackground(new java.awt.Color(49, 49, 186));
        btn_Clear.setFont(new java.awt.Font("Ubisoft Sans", 1, 12)); // NOI18N
        btn_Clear.setForeground(new java.awt.Color(255, 255, 255));
        btn_Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/refresh.png"))); // NOI18N
        btn_Clear.setText("CLEAR");
        btn_Clear.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClearActionPerformed(evt);
            }
        });

        lbl_nopol.setFont(new java.awt.Font("Ubisoft Sans", 0, 18)); // NOI18N
        lbl_nopol.setText("NO POLISI                         :");

        lbl_unit.setFont(new java.awt.Font("Ubisoft Sans", 0, 18)); // NOI18N
        lbl_unit.setText("UNIT                                    :");

        lbl_harga.setFont(new java.awt.Font("Ubisoft Sans", 0, 18)); // NOI18N
        lbl_harga.setText("HARGA SEWA/HARI     :");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/res_car_us.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbl_unit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_unit, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(lbl_nopol, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_nopol, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbl_harga)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btn_Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(btn_Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nopol, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_nopol))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_unit)
                            .addComponent(txt_unit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_harga)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nopolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nopolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nopolActionPerformed

    private void txt_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hargaActionPerformed

    private void btn_TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TambahActionPerformed
        String nopol = txt_nopol.getText();
        String unit = txt_unit.getText();
        String harga = txt_harga.getText();

        if (nopol.isEmpty() || unit.isEmpty() || harga.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mohon lengkapi semua data", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        con = Basisdata.getKoneksi();
        String sql = "INSERT INTO Kendaraan (No_Polisi, Unit, Harga_Sewa_Per_Hari) VALUES (?, ?, ?)";
        try{
            pst = con.prepareStatement(sql);
            pst.setString(1, nopol);
            pst.setString(2, unit);
            pst.setString(3, harga);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil ditambah", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        clear();
        update_table();
    }//GEN-LAST:event_btn_TambahActionPerformed

    private void btn_KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KembaliActionPerformed
        new Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_KembaliActionPerformed

    private void txt_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cariActionPerformed
        cari();
    }//GEN-LAST:event_txt_cariActionPerformed

    private void txt_unitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_unitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_unitActionPerformed

    private void btn_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HapusActionPerformed
        String nopol = txt_nopol.getText();
        
        if (nopol.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mohon isi nomor polisi yang ingin dihapus", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String sqlCekNopol = "SELECT COUNT(*) FROM Kendaraan WHERE No_Polisi=?";
        try {
            pst = con.prepareStatement(sqlCekNopol);
            pst.setString(1, nopol);
            rs = pst.executeQuery();
            rs.next();
            int count = rs.getInt(1);
            if (count == 0) {
                JOptionPane.showMessageDialog(this, "Nomor Polisi tidak ditemukan", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        int selectedOption = JOptionPane.showConfirmDialog(null, "Hapus data dengan nomor polisi : "+nopol+"?","Konformasi", JOptionPane.INFORMATION_MESSAGE);
        if(selectedOption == JOptionPane.YES_OPTION){
            con = Basisdata.getKoneksi();
            try{
                String sql = "DELETE FROM Kendaraan WHERE No_Polisi=?";
                pst = con.prepareStatement(sql);
                pst.setString(1, nopol);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
            } 
            catch(SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        clear();
        update_table();
    }//GEN-LAST:event_btn_HapusActionPerformed

    private void btn_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditActionPerformed
        String nopol = txt_nopol.getText();
        String unit = txt_unit.getText();
        String harga = txt_harga.getText();

        if (nopol.isEmpty() || unit.isEmpty() || harga.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mohon lengkapi semua data", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        con = Basisdata.getKoneksi();
        String sqlCekNama = "SELECT COUNT(*) FROM Kendaraan WHERE No_Polisi=?";
        try {
            pst = con.prepareStatement(sqlCekNama);
            pst.setString(1, nopol);
            rs = pst.executeQuery();
            rs.next();
            int count = rs.getInt(1);
            if (count == 0) {
                JOptionPane.showMessageDialog(this, "Nomor Polisi tidak ditemukan", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

        String sql = "UPDATE Kendaraan SET Unit=?, Harga_Sewa_Per_Hari=? WHERE No_Polisi=?";
        try{
            pst = con.prepareStatement(sql);
            pst.setString(1, unit);
            pst.setString(2, harga);
            pst.setString(3, nopol);  
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil diedit", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        clear();
        update_table();
    }//GEN-LAST:event_btn_EditActionPerformed

    private void btn_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClearActionPerformed
        clear();
    }//GEN-LAST:event_btn_ClearActionPerformed

    private void table_KendaraanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_KendaraanMouseClicked
        DefaultTableModel tabel = (DefaultTableModel) table_Kendaraan.getModel();
        int selectedIndex = table_Kendaraan.getSelectedRow();
        
        txt_nopol.setText(tabel.getValueAt(selectedIndex, 0).toString());
        txt_unit.setText(tabel.getValueAt(selectedIndex, 1).toString());
        txt_harga.setText(tabel.getValueAt(selectedIndex, 2).toString());
    }//GEN-LAST:event_table_KendaraanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kendaraan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kendaraan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kendaraan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kendaraan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kendaraan().setVisible(true);
            }
        });
    }

    private void clear() {
        txt_nopol.setText("");
        txt_unit.setText("");
        txt_harga.setText("");
    }
    
    private void cari(){
        try{
            st = Basisdata.getKoneksi().createStatement();
            rs = st.executeQuery("SELECT * FROM Kendaraan WHERE No_Polisi LIKE '%"+txt_cari.getText()+"%'");
            dtm.getDataVector().removeAllElements();
            while(rs.next()){
                Object[] x = new Object[3];
                    x[0] = rs.getString("No_Polisi");
                    x[1] = rs.getString("Unit");
                    x[2] = rs.getString("Harga_Sewa_Per_Hari");
                    dtm.addRow(x);
            }
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi error", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    private void update_table(){
        dtm.getDataVector().removeAllElements();
        dtm.fireTableDataChanged();
        try{
            con = Basisdata.getKoneksi();
            try(Statement s = con.createStatement()){
                String sql = "SELECT * FROM Kendaraan";
                rs = s.executeQuery(sql);
                while(rs.next()){
                    Object[] x = new Object[3];
                    x[0] = rs.getString("No_Polisi");
                    x[1] = rs.getString("Unit");
                    x[2] = rs.getString("Harga_Sewa_Per_Hari");
                    dtm.addRow(x);
                }
                rs.close();
            }
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error");
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Clear;
    private javax.swing.JButton btn_Edit;
    private javax.swing.JButton btn_Hapus;
    private javax.swing.JButton btn_Kembali;
    private javax.swing.JButton btn_Tambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel lbl_harga;
    private javax.swing.JLabel lbl_nopol;
    private javax.swing.JLabel lbl_unit;
    private javax.swing.JTable table_Kendaraan;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_nopol;
    private javax.swing.JTextField txt_unit;
    // End of variables declaration//GEN-END:variables
}
