/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package basisdata;

import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aril
 */
public class Penyewa extends javax.swing.JFrame {
    PreparedStatement pst = null;
    ResultSet rs;
    Statement st;
    Connection con;
    final DefaultTableModel dtm;

    public Penyewa() {
        initComponents();
        dtm = new DefaultTableModel();
        table_Penyewa.setModel(dtm);
        dtm.addColumn("Nama Penyewa");
        dtm.addColumn("Nomor Telepon");
        dtm.addColumn("Alamat");
        update_table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txt_nama = new javax.swing.JTextField();
        txt_telp = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();
        btn_Tambah = new javax.swing.JButton();
        btn_Hapus = new javax.swing.JButton();
        btn_Edit = new javax.swing.JButton();
        btn_Kembali = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_cari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Penyewa = new javax.swing.JTable();
        btn_Clear = new javax.swing.JButton();
        lbl_nama = new javax.swing.JLabel();
        lbl_telp = new javax.swing.JLabel();
        lbl_alamat = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("1001 Trans Malang");
        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(1000, 800));
        setSize(new java.awt.Dimension(1000, 800));

        jPanel1.setBackground(new java.awt.Color(200, 48, 97));

        judul.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        judul.setForeground(new java.awt.Color(235, 184, 66));
        judul.setText("DATA PENYEWA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(judul)
                .addGap(353, 353, 353))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judul, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(239, 241, 236));

        txt_nama.setFont(new java.awt.Font("Ubisoft Sans", 0, 14)); // NOI18N
        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });

        txt_telp.setFont(new java.awt.Font("Ubisoft Sans", 0, 14)); // NOI18N

        txt_alamat.setFont(new java.awt.Font("Ubisoft Sans", 0, 14)); // NOI18N
        txt_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_alamatActionPerformed(evt);
            }
        });

        btn_Tambah.setBackground(new java.awt.Color(31, 63, 102));
        btn_Tambah.setFont(new java.awt.Font("Ubisoft Sans", 1, 12)); // NOI18N
        btn_Tambah.setForeground(new java.awt.Color(255, 255, 255));
        btn_Tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plus.png"))); // NOI18N
        btn_Tambah.setText("TAMBAH DATA");
        btn_Tambah.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TambahActionPerformed(evt);
            }
        });

        btn_Hapus.setBackground(new java.awt.Color(31, 63, 102));
        btn_Hapus.setFont(new java.awt.Font("Ubisoft Sans", 1, 12)); // NOI18N
        btn_Hapus.setForeground(new java.awt.Color(255, 255, 255));
        btn_Hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/trash_box.png"))); // NOI18N
        btn_Hapus.setText("HAPUS DATA");
        btn_Hapus.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HapusActionPerformed(evt);
            }
        });

        btn_Edit.setBackground(new java.awt.Color(31, 63, 102));
        btn_Edit.setFont(new java.awt.Font("Ubisoft Sans", 1, 12)); // NOI18N
        btn_Edit.setForeground(new java.awt.Color(255, 255, 255));
        btn_Edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pencil_edit.png"))); // NOI18N
        btn_Edit.setText("EDIT DATA");
        btn_Edit.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditActionPerformed(evt);
            }
        });

        btn_Kembali.setBackground(new java.awt.Color(31, 63, 102));
        btn_Kembali.setFont(new java.awt.Font("Ubisoft Sans", 1, 12)); // NOI18N
        btn_Kembali.setForeground(new java.awt.Color(255, 255, 255));
        btn_Kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/arrow_left.png"))); // NOI18N
        btn_Kembali.setText("BACK");
        btn_Kembali.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KembaliActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Ubisoft Sans", 0, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search_lense.png"))); // NOI18N
        jLabel1.setText("CARI");

        txt_cari.setFont(new java.awt.Font("Ubisoft Sans", 0, 12)); // NOI18N
        txt_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txt_cari, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_cari))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleParent(jPanel3);
        txt_cari.getAccessibleContext().setAccessibleParent(jPanel3);

        table_Penyewa.setBackground(new java.awt.Color(200, 48, 97));
        table_Penyewa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 49, 49), 1, true));
        table_Penyewa.setFont(new java.awt.Font("Ubisoft Sans", 0, 14)); // NOI18N
        table_Penyewa.setForeground(new java.awt.Color(255, 255, 255));
        table_Penyewa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        table_Penyewa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        table_Penyewa.setGridColor(new java.awt.Color(255, 255, 255));
        table_Penyewa.setRowHeight(25);
        table_Penyewa.setSelectionBackground(new java.awt.Color(31, 63, 102));
        table_Penyewa.setShowGrid(true);
        table_Penyewa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_PenyewaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_Penyewa);
        table_Penyewa.getAccessibleContext().setAccessibleParent(jPanel3);

        btn_Clear.setBackground(new java.awt.Color(31, 63, 102));
        btn_Clear.setFont(new java.awt.Font("Ubisoft Sans", 1, 12)); // NOI18N
        btn_Clear.setForeground(new java.awt.Color(255, 255, 255));
        btn_Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/refresh.png"))); // NOI18N
        btn_Clear.setText("CLEAR");
        btn_Clear.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClearActionPerformed(evt);
            }
        });

        lbl_nama.setFont(new java.awt.Font("Ubisoft Sans", 1, 18)); // NOI18N
        lbl_nama.setForeground(new java.awt.Color(31, 63, 102));
        lbl_nama.setText("NAMA                         :");

        lbl_telp.setFont(new java.awt.Font("Ubisoft Sans", 1, 18)); // NOI18N
        lbl_telp.setForeground(new java.awt.Color(31, 63, 102));
        lbl_telp.setText("NO TELEPON           :");

        lbl_alamat.setFont(new java.awt.Font("Ubisoft Sans", 1, 18)); // NOI18N
        lbl_alamat.setForeground(new java.awt.Color(31, 63, 102));
        lbl_alamat.setText("ALAMAT                    :");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user_tambah_icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_alamat)
                            .addComponent(lbl_telp, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_alamat)
                            .addComponent(txt_telp)
                            .addComponent(txt_nama, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btn_Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(btn_Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(67, 67, 67))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_nama))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_telp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_telp))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_alamat)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        txt_nama.getAccessibleContext().setAccessibleParent(jPanel3);
        txt_telp.getAccessibleContext().setAccessibleParent(jPanel3);
        txt_alamat.getAccessibleContext().setAccessibleParent(jPanel3);
        btn_Tambah.getAccessibleContext().setAccessibleParent(jPanel3);
        btn_Hapus.getAccessibleContext().setAccessibleParent(jPanel3);
        btn_Edit.getAccessibleContext().setAccessibleParent(jPanel3);
        btn_Kembali.getAccessibleContext().setAccessibleParent(jPanel3);
        jPanel2.getAccessibleContext().setAccessibleParent(jPanel3);
        jScrollPane1.getAccessibleContext().setAccessibleParent(jPanel3);
        btn_Clear.getAccessibleContext().setAccessibleParent(jPanel3);
        lbl_nama.getAccessibleContext().setAccessibleParent(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed

    private void txt_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_alamatActionPerformed

    private void btn_KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KembaliActionPerformed
        new Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_KembaliActionPerformed

    private void txt_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cariActionPerformed
        cari();
    }//GEN-LAST:event_txt_cariActionPerformed

    private void btn_TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TambahActionPerformed
        String nama = txt_nama.getText();
        String telp = txt_telp.getText();
        String alamat = txt_alamat.getText();

        if (nama.isEmpty() || telp.isEmpty() || alamat.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mohon lengkapi semua data", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        con = Basisdata.getKoneksi();
        String sql = "INSERT INTO Penyewa (Nama_Penyewa, Nomor_Telepon, Alamat) VALUES (?, ?, ?)";
        try{
            pst = con.prepareStatement(sql);
            pst.setString(1, nama);
            pst.setString(2, telp);
            pst.setString(3, alamat);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil ditambah", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        clear();
        update_table();
    }//GEN-LAST:event_btn_TambahActionPerformed

    private void btn_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClearActionPerformed
        clear();
    }//GEN-LAST:event_btn_ClearActionPerformed

    private void btn_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditActionPerformed
        String nama = txt_nama.getText();
        String telp = txt_telp.getText();
        String alamat = txt_alamat.getText();

        if (nama.isEmpty() || telp.isEmpty() || alamat.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mohon lengkapi semua data", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        con = Basisdata.getKoneksi();
        String sqlCekNama = "SELECT COUNT(*) FROM Penyewa WHERE Nama_Penyewa=?";
        try {
            pst = con.prepareStatement(sqlCekNama);
            pst.setString(1, nama);
            rs = pst.executeQuery();
            rs.next();
            int count = rs.getInt(1);
            if (count == 0) {
                JOptionPane.showMessageDialog(this, "Nama penyewa tidak ditemukan", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

        String sql = "UPDATE Penyewa SET Nomor_Telepon=?, Alamat=? WHERE Nama_Penyewa=?";
        try{
            pst = con.prepareStatement(sql);
            pst.setString(1, telp);
            pst.setString(2, alamat);
            pst.setString(3, nama);  
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil diedit", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        clear();
        update_table();
    }//GEN-LAST:event_btn_EditActionPerformed

    private void btn_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HapusActionPerformed
        String nama = txt_nama.getText();
        
        if (nama.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mohon isi nama yang ingin dihapus", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String sqlCekNama = "SELECT COUNT(*) FROM Penyewa WHERE Nama_Penyewa=?";
        try {
            pst = con.prepareStatement(sqlCekNama);
            pst.setString(1, nama);
            rs = pst.executeQuery();
            rs.next();
            int count = rs.getInt(1);
            if (count == 0) {
                JOptionPane.showMessageDialog(this, "Nama penyewa tidak ditemukan", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        int selectedOption = JOptionPane.showConfirmDialog(null, "Hapus data dengan nama : "+nama+"?","Konformasi", JOptionPane.INFORMATION_MESSAGE);
        if(selectedOption == JOptionPane.YES_OPTION){
            con = Basisdata.getKoneksi();
            try{
                String sql = "DELETE FROM Penyewa WHERE Nama_Penyewa=?";
                pst = con.prepareStatement(sql);
                pst.setString(1, nama);
                pst.executeUpdate();
                
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
            } 
            catch(SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        clear();
        update_table();
    }//GEN-LAST:event_btn_HapusActionPerformed

    private void table_PenyewaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_PenyewaMouseClicked
        DefaultTableModel tabel = (DefaultTableModel) table_Penyewa.getModel();
        int selectedIndex = table_Penyewa.getSelectedRow();
        
        txt_nama.setText(tabel.getValueAt(selectedIndex, 0).toString());
        txt_telp.setText(tabel.getValueAt(selectedIndex, 1).toString());
        txt_alamat.setText(tabel.getValueAt(selectedIndex, 2).toString());
    }//GEN-LAST:event_table_PenyewaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Penyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Penyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Penyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Penyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Penyewa().setVisible(true);
            }
        });
    }
    
    private void clear() {
        txt_nama.setText("");
        txt_telp.setText("");
        txt_alamat.setText("");
    }
    
    private void update_table(){
        dtm.getDataVector().removeAllElements();
        dtm.fireTableDataChanged();
        try{
            con = Basisdata.getKoneksi();
            try(Statement s = con.createStatement()){
                String sql = "SELECT * FROM Penyewa";
                rs = s.executeQuery(sql);
                while(rs.next()){
                    Object[] x = new Object[3];
                    x[0] = rs.getString("Nama_Penyewa");
                    x[1] = rs.getString("Nomor_Telepon");
                    x[2] = rs.getString("Alamat");
                    dtm.addRow(x);
                }
                rs.close();
            }
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error");
        }
    }
    
    private void cari(){
        try{
            st = Basisdata.getKoneksi().createStatement();
            rs = st.executeQuery("SELECT * FROM Penyewa WHERE Nama_Penyewa LIKE '%"+txt_cari.getText()+"%'");
            dtm.getDataVector().removeAllElements();
            while(rs.next()){
                Object[] x = new Object[3];
                    x[0] = rs.getString("Nama_Penyewa");
                    x[1] = rs.getString("Nomor_Telepon");
                    x[2] = rs.getString("Alamat");
                    dtm.addRow(x);
            }
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi error", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Clear;
    private javax.swing.JButton btn_Edit;
    private javax.swing.JButton btn_Hapus;
    private javax.swing.JButton btn_Kembali;
    private javax.swing.JButton btn_Tambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel lbl_alamat;
    private javax.swing.JLabel lbl_nama;
    private javax.swing.JLabel lbl_telp;
    private javax.swing.JTable table_Penyewa;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_telp;
    // End of variables declaration//GEN-END:variables
}
