/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package basisdata;

import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aril
 */
public class Penyewaan extends javax.swing.JFrame {
    PreparedStatement pst = null;
    ResultSet rs;
    Statement st;
    Connection con;
    final DefaultTableModel dtm;
    
    public Penyewaan() {
        initComponents();
        txt_pemilik.setText("1001");
        
        dtm = new DefaultTableModel();
        table_Penyewaan.setModel(dtm);
        dtm.addColumn("Nomor Transaksi");
        dtm.addColumn("Nama Penyewa");
        dtm.addColumn("Pemilik Unit");
        dtm.addColumn("Keterangan");
        dtm.addColumn("Alamat Pengambilan");
        dtm.addColumn("Alamat Pengembalian");
        dtm.addColumn("Jaminan");
        update_table();
        nama();
    }
    
    public void nama(){
        try{
            con = Basisdata.getKoneksi();
            st = con.createStatement();
            String sql = "SELECT Nama_Penyewa FROM Penyewa";
            rs = st.executeQuery(sql);
            
            while(rs.next()){
                String nama = rs.getString("Nama_Penyewa");
                box_nama.addItem(nama);
            }
        }
        catch(SQLException e){
            Logger.getLogger(Penyewaan.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txt_pemilik = new javax.swing.JTextField();
        btn_Tambah = new javax.swing.JButton();
        btn_Hapus = new javax.swing.JButton();
        btn_Edit = new javax.swing.JButton();
        btn_Kembali = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_cari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Penyewaan = new javax.swing.JTable();
        btn_Clear = new javax.swing.JButton();
        lbl_nopol = new javax.swing.JLabel();
        lbl_unit = new javax.swing.JLabel();
        box_nama = new javax.swing.JComboBox<>();
        lbl_tglSewa = new javax.swing.JLabel();
        lbl_tglKembali = new javax.swing.JLabel();
        lbl_btsWkt = new javax.swing.JLabel();
        lbl_nama = new javax.swing.JLabel();
        box_keterangan = new javax.swing.JComboBox<>();
        txt_almtKembali = new javax.swing.JTextField();
        txt_almtAmbil = new javax.swing.JTextField();
        txt_jaminan = new javax.swing.JTextField();
        lbl_noTrans = new javax.swing.JLabel();
        txt_noTrans = new javax.swing.JTextField();
        btn_next = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("1001 Trans Malang");
        setPreferredSize(new java.awt.Dimension(1042, 822));

        jPanel1.setBackground(new java.awt.Color(200, 49, 49));

        judul.setFont(new java.awt.Font("Ubisoft Sans", 1, 36)); // NOI18N
        judul.setText("PENYEWAAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(judul)
                .addGap(391, 391, 391))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judul, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(45, 193, 193));

        txt_pemilik.setFont(new java.awt.Font("Ubisoft Sans", 0, 12)); // NOI18N

        btn_Tambah.setBackground(new java.awt.Color(49, 49, 186));
        btn_Tambah.setFont(new java.awt.Font("Ubisoft Sans", 1, 12)); // NOI18N
        btn_Tambah.setForeground(new java.awt.Color(255, 255, 255));
        btn_Tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plus.png"))); // NOI18N
        btn_Tambah.setText("TAMBAH DATA");
        btn_Tambah.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TambahActionPerformed(evt);
            }
        });

        btn_Hapus.setBackground(new java.awt.Color(49, 49, 186));
        btn_Hapus.setFont(new java.awt.Font("Ubisoft Sans", 1, 12)); // NOI18N
        btn_Hapus.setForeground(new java.awt.Color(255, 255, 255));
        btn_Hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/trash_box.png"))); // NOI18N
        btn_Hapus.setText("HAPUS DATA");
        btn_Hapus.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HapusActionPerformed(evt);
            }
        });

        btn_Edit.setBackground(new java.awt.Color(49, 49, 186));
        btn_Edit.setFont(new java.awt.Font("Ubisoft Sans", 1, 12)); // NOI18N
        btn_Edit.setForeground(new java.awt.Color(255, 255, 255));
        btn_Edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pencil_edit.png"))); // NOI18N
        btn_Edit.setText("EDIT DATA");
        btn_Edit.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditActionPerformed(evt);
            }
        });

        btn_Kembali.setFont(new java.awt.Font("Ubisoft Sans", 1, 12)); // NOI18N
        btn_Kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/arrow_left.png"))); // NOI18N
        btn_Kembali.setText("BACK");
        btn_Kembali.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KembaliActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Ubisoft Sans", 0, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search_lense.png"))); // NOI18N
        jLabel1.setText("CARI");

        txt_cari.setFont(new java.awt.Font("Ubisoft Sans", 0, 12)); // NOI18N
        txt_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txt_cari, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_cari))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        table_Penyewaan.setBackground(new java.awt.Color(200, 49, 49));
        table_Penyewaan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 49, 49), 1, true));
        table_Penyewaan.setFont(new java.awt.Font("Ubisoft Sans", 0, 12)); // NOI18N
        table_Penyewaan.setForeground(new java.awt.Color(255, 255, 255));
        table_Penyewaan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        table_Penyewaan.setGridColor(new java.awt.Color(255, 255, 255));
        table_Penyewaan.setRowHeight(25);
        table_Penyewaan.setSelectionBackground(new java.awt.Color(204, 204, 204));
        table_Penyewaan.setShowGrid(true);
        table_Penyewaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_PenyewaanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                table_PenyewaanMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table_PenyewaanMousePressed(evt);
            }
        });
        table_Penyewaan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                table_PenyewaanKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(table_Penyewaan);

        btn_Clear.setBackground(new java.awt.Color(49, 49, 186));
        btn_Clear.setFont(new java.awt.Font("Ubisoft Sans", 1, 12)); // NOI18N
        btn_Clear.setForeground(new java.awt.Color(255, 255, 255));
        btn_Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/refresh.png"))); // NOI18N
        btn_Clear.setText("CLEAR");
        btn_Clear.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClearActionPerformed(evt);
            }
        });

        lbl_nopol.setFont(new java.awt.Font("Ubisoft Sans", 0, 14)); // NOI18N
        lbl_nopol.setText("PEMILIK UNIT             :");

        lbl_unit.setFont(new java.awt.Font("Ubisoft Sans", 0, 14)); // NOI18N
        lbl_unit.setText("KETERANGAN          :");

        box_nama.setFont(new java.awt.Font("Ubisoft Sans", 0, 12)); // NOI18N

        lbl_tglSewa.setFont(new java.awt.Font("Ubisoft Sans", 0, 14)); // NOI18N
        lbl_tglSewa.setText("ALAMAT PENGAMBILAN      :");

        lbl_tglKembali.setFont(new java.awt.Font("Ubisoft Sans", 0, 14)); // NOI18N
        lbl_tglKembali.setText("ALAMAT PENGEMBALIAN   :");

        lbl_btsWkt.setFont(new java.awt.Font("Ubisoft Sans", 0, 14)); // NOI18N
        lbl_btsWkt.setText("JAMINAN                                   :");

        lbl_nama.setFont(new java.awt.Font("Ubisoft Sans", 0, 14)); // NOI18N
        lbl_nama.setText("NAMA PENYEWA     :");

        box_keterangan.setFont(new java.awt.Font("Ubisoft Sans", 0, 12)); // NOI18N
        box_keterangan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ambil Sendiri", "Diantar" }));

        txt_almtKembali.setFont(new java.awt.Font("Ubisoft Sans", 0, 12)); // NOI18N

        txt_almtAmbil.setFont(new java.awt.Font("Ubisoft Sans", 0, 12)); // NOI18N
        txt_almtAmbil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_almtAmbilActionPerformed(evt);
            }
        });

        txt_jaminan.setFont(new java.awt.Font("Ubisoft Sans", 0, 12)); // NOI18N
        txt_jaminan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jaminanActionPerformed(evt);
            }
        });

        lbl_noTrans.setFont(new java.awt.Font("Ubisoft Sans", 0, 14)); // NOI18N
        lbl_noTrans.setText("Nomor Transaksi       :");

        txt_noTrans.setFont(new java.awt.Font("Ubisoft Sans", 0, 12)); // NOI18N
        txt_noTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_noTransActionPerformed(evt);
            }
        });

        btn_next.setFont(new java.awt.Font("Ubisoft Sans", 1, 12)); // NOI18N
        btn_next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/arrow_right.png"))); // NOI18N
        btn_next.setText("NEXT");
        btn_next.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbl_noTrans, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_noTrans, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_unit, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_nopol))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_pemilik, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(box_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(box_keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_tglKembali, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_btsWkt, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(lbl_tglSewa)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_almtAmbil, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_jaminan, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_almtKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_next, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tglSewa)
                    .addComponent(txt_almtAmbil, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_noTrans)
                    .addComponent(txt_noTrans, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_tglKembali)
                            .addComponent(txt_almtKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_btsWkt)
                            .addComponent(txt_jaminan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_nama)
                            .addComponent(box_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_nopol)
                            .addComponent(txt_pemilik, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_unit)
                            .addComponent(box_keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_next, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TambahActionPerformed
        String nama = box_nama.getSelectedItem().toString();
        String pemilik = txt_pemilik.getText();
        String keterangan = box_keterangan.getSelectedItem().toString();
        String almt_ambil = txt_almtAmbil.getText();
        String almt_kembali = txt_almtKembali.getText();
        String jaminan = txt_jaminan.getText();

        if (almt_ambil.isEmpty() || almt_kembali.isEmpty() || jaminan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mohon lengkapi semua data", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        con = Basisdata.getKoneksi();
        String sql = "INSERT INTO Penyewaan (Nama_Penyewa, Pemilik_Unit, Keterangan, Alamat_Pengambilan, Alamat_Pengembalian, Jaminan) VALUES (?, ?, ?, ?, ?, ?)";
        try{
            pst = con.prepareStatement(sql);
            pst.setString(1, nama);
            pst.setString(2, pemilik);
            pst.setString(3, keterangan);
            pst.setString(4, almt_ambil);
            pst.setString(5, almt_kembali);
            pst.setString(6, jaminan);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil ditambah", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        clear();
        update_table();
    }//GEN-LAST:event_btn_TambahActionPerformed

    private void btn_KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KembaliActionPerformed
        new Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_KembaliActionPerformed

    private void txt_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cariActionPerformed
        cari();
    }//GEN-LAST:event_txt_cariActionPerformed

    private void txt_almtAmbilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_almtAmbilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_almtAmbilActionPerformed

    private void txt_jaminanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jaminanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jaminanActionPerformed

    private void btn_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClearActionPerformed
        clear();
    }//GEN-LAST:event_btn_ClearActionPerformed

    private void btn_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HapusActionPerformed
        String nomTrans = txt_noTrans.getText();
        
        if (nomTrans.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mohon isi nomor transaksi yang ingin dihapus", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String sqlCekNomTrans = "SELECT COUNT(*) FROM Penyewaan WHERE No_Transaksi=?";
        try {
            pst = con.prepareStatement(sqlCekNomTrans);
            pst.setString(1, nomTrans);
            rs = pst.executeQuery();
            rs.next();
            int count = rs.getInt(1);
            if (count == 0) {
                JOptionPane.showMessageDialog(this, "Nomor Transaksi tidak ditemukan", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        int selectedOption = JOptionPane.showConfirmDialog(null, "Hapus data dengan nomor Transaksi : "+nomTrans+"?","Konformasi", JOptionPane.INFORMATION_MESSAGE);
        if(selectedOption == JOptionPane.YES_OPTION){
            con = Basisdata.getKoneksi();
            try{
                String sql = "DELETE FROM Penyewaan WHERE No_Transaksi=?";
                pst = con.prepareStatement(sql);
                pst.setString(1, nomTrans);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
            } 
            catch(SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        clear();
        update_table();
    }//GEN-LAST:event_btn_HapusActionPerformed

    private void txt_noTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_noTransActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_noTransActionPerformed

    private void table_PenyewaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_PenyewaanMouseClicked
        DefaultTableModel tabel = (DefaultTableModel) table_Penyewaan.getModel();
        int selectedIndex = table_Penyewaan.getSelectedRow();
        
        txt_noTrans.setText(tabel.getValueAt(selectedIndex, 0).toString());
        box_nama.setSelectedItem(tabel.getValueAt(selectedIndex, 1).toString());
        txt_pemilik.setText(tabel.getValueAt(selectedIndex, 2).toString());
        box_keterangan.setSelectedItem(tabel.getValueAt(selectedIndex, 3).toString());
        txt_almtAmbil.setText(tabel.getValueAt(selectedIndex, 4).toString());
        txt_almtKembali.setText(tabel.getValueAt(selectedIndex, 5).toString());
        txt_jaminan.setText(tabel.getValueAt(selectedIndex, 6).toString());
    }//GEN-LAST:event_table_PenyewaanMouseClicked

    private void btn_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditActionPerformed
        String nomTrans = txt_noTrans.getText();
        String nama = box_nama.getSelectedItem().toString();
        String pemilik = txt_pemilik.getText();
        String keterangan = box_keterangan.getSelectedItem().toString();
        String almt_ambil = txt_almtAmbil.getText();
        String almt_kembali = txt_almtKembali.getText();
        String jaminan = txt_jaminan.getText();

        if (nomTrans.isEmpty() || almt_ambil.isEmpty() || almt_kembali.isEmpty() || jaminan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mohon lengkapi semua data", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        con = Basisdata.getKoneksi();
        String sqlCekNama = "SELECT COUNT(*) FROM Penyewaan WHERE No_Transaksi=?";
        try {
            pst = con.prepareStatement(sqlCekNama);
            pst.setString(1, nomTrans);
            rs = pst.executeQuery();
            rs.next();
            int count = rs.getInt(1);
            if (count == 0) {
                JOptionPane.showMessageDialog(this, "Nomor Transaksi tidak ditemukan", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

        String sql = "UPDATE Penyewaan SET Nama_Penyewa=?, Pemilik_Unit=?, Keterangan=?, Alamat_Pengambilan=?, Alamat_Pengembalian=?, Jaminan=? WHERE No_Transaksi=?";
        try{
            pst = con.prepareStatement(sql);
            pst.setString(1, nama);
            pst.setString(2, pemilik);
            pst.setString(3, keterangan);
            pst.setString(4, almt_ambil);
            pst.setString(5, almt_kembali);
            pst.setString(6, jaminan);  
            pst.setString(7, nomTrans);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil diedit", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        clear();
        update_table();
    }//GEN-LAST:event_btn_EditActionPerformed

    private void table_PenyewaanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_PenyewaanMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_table_PenyewaanMouseEntered

    private void table_PenyewaanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_PenyewaanMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_table_PenyewaanMousePressed

    private void table_PenyewaanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_table_PenyewaanKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_table_PenyewaanKeyPressed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        String nomTrans = txt_noTrans.getText();
        
        int selectedOption = JOptionPane.showConfirmDialog(null, "Ingin melanjutkan ke detail penyewaan dengan nomor transaksi : " +nomTrans+"?","Konformasi", JOptionPane.INFORMATION_MESSAGE);
        if(selectedOption == JOptionPane.YES_OPTION){
            new detailPenyewaan(nomTrans).setVisible(true);
                this.dispose();
        }
    }//GEN-LAST:event_btn_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Penyewaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Penyewaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Penyewaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Penyewaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Penyewaan().setVisible(true);
            }
        });
    }
    
    private void clear() {
        txt_noTrans.setText("");
        txt_pemilik.setText("1001");
        txt_almtAmbil.setText("");
        txt_almtKembali.setText("");
        txt_jaminan.setText("");
    }
    
    private void cari(){
        try{
            st = Basisdata.getKoneksi().createStatement();
            rs = st.executeQuery("SELECT * FROM Penyewaan WHERE No_Transaksi LIKE '%"+txt_cari.getText()+"%'");
            dtm.getDataVector().removeAllElements();
            while(rs.next()){
                Object[] x = new Object[7];
                    x[0] = rs.getString("No_Transaksi");
                    x[1] = rs.getString("Nama_Penyewa");
                    x[2] = rs.getString("Pemilik_Unit");
                    x[3] = rs.getString("Keterangan");
                    x[4] = rs.getString("Alamat_Pengambilan");
                    x[5] = rs.getString("Alamat_Pengembalian");
                    x[6] = rs.getString("Jaminan");
                    dtm.addRow(x);
            }
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi error", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    private void update_table(){
        dtm.getDataVector().removeAllElements();
        dtm.fireTableDataChanged();
        try{
            con = Basisdata.getKoneksi();
            try(Statement s = con.createStatement()){
                String sql = "SELECT * FROM Penyewaan";
                rs = s.executeQuery(sql);
                while(rs.next()){
                    Object[] x = new Object[7];
                    x[0] = rs.getString("No_Transaksi");
                    x[1] = rs.getString("Nama_Penyewa");
                    x[2] = rs.getString("Pemilik_Unit");
                    x[3] = rs.getString("Keterangan");
                    x[4] = rs.getString("Alamat_Pengambilan");
                    x[5] = rs.getString("Alamat_Pengembalian");
                    x[6] = rs.getString("Jaminan");
                    dtm.addRow(x);
                }
                rs.close();
            }
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> box_keterangan;
    private javax.swing.JComboBox<String> box_nama;
    private javax.swing.JButton btn_Clear;
    private javax.swing.JButton btn_Edit;
    private javax.swing.JButton btn_Hapus;
    private javax.swing.JButton btn_Kembali;
    private javax.swing.JButton btn_Tambah;
    private javax.swing.JButton btn_next;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel lbl_btsWkt;
    private javax.swing.JLabel lbl_nama;
    private javax.swing.JLabel lbl_noTrans;
    private javax.swing.JLabel lbl_nopol;
    private javax.swing.JLabel lbl_tglKembali;
    private javax.swing.JLabel lbl_tglSewa;
    private javax.swing.JLabel lbl_unit;
    private javax.swing.JTable table_Penyewaan;
    private javax.swing.JTextField txt_almtAmbil;
    private javax.swing.JTextField txt_almtKembali;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_jaminan;
    private javax.swing.JTextField txt_noTrans;
    private javax.swing.JTextField txt_pemilik;
    // End of variables declaration//GEN-END:variables
}
